-- alter table SD_Course AUTO_INCREMENT=1;

-- SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for SD_Course
-- ----------------------------
-- DROP TABLE IF EXISTS `SD_Course`;
-- CREATE TABLE `SD_Course` (
--   `id` int(11) NOT NULL AUTO_INCREMENT,
--   `code` varchar(11) DEFAULT NULL,
--   `courseName` varchar(50) DEFAULT NULL,
--   `date` varchar(50) DEFAULT NULL,
--   `openid` varchar(50) DEFAULT NULL,
--   `isDelete` INT(2) DEFAULT 0,
--   `con1` varchar(50) DEFAULT NULL,
--   `con2` varchar(50) DEFAULT NULL,
--   `con3` varchar(50) DEFAULT NULL,
--   `con4` varchar(50) DEFAULT NULL,
--   `con5` varchar(50) DEFAULT NULL,
--   PRIMARY KEY (`id`)
-- ) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;