-- alter table SD_Relation AUTO_INCREMENT=1;

-- SET FOREIGN_KEY_CHECKS=0;
--
-- ----------------------------
-- Table structure for SD_Relation
-- ----------------------------
-- DROP TABLE IF EXISTS `SD_Relation`;
-- CREATE TABLE `SD_Relation` (
--   `id` int(11) NOT NULL AUTO_INCREMENT,
--   `openid` varchar(50) DEFAULT NULL,
--   `code` varchar(11) DEFAULT NULL,
--   `isDelete` INT (2) DEFAULT 0,
--   `con1` varchar(255) DEFAULT NULL,
--   `con2` varchar(255) DEFAULT NULL,
--   PRIMARY KEY (`id`)
-- ) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;