-- alter table SD_Reply AUTO_INCREMENT=1;

-- SET FOREIGN_KEY_CHECKS=0;

-- ----------------------------
-- Table structure for SD_Reply
-- ----------------------------
-- DROP TABLE IF EXISTS `SD_Reply`;
-- CREATE TABLE `SD_Reply` (
--   `id` int(11) NOT NULL AUTO_INCREMENT,
--   `codeid` varchar(11) DEFAULT NULL,  -- homework的 code 和 id
--   `openid` varchar(50) DEFAULT NULL,
--   `imgurl` varchar(50) DEFAULT NULL,
--   `content` varchar(600) DEFAULT NULL,
--   `date` varchar(30) DEFAULT NULL,
--   `isDelete` INT (2) DEFAULT 0,
--   `factor1` varchar(50) DEFAULT NULL,
--   `factor2` varchar(50) DEFAULT NULL,
--   `factor3` varchar(50) DEFAULT NULL,
--   `factor4` varchar(50) DEFAULT NULL,
--   `factor5` varchar(50) DEFAULT NULL,
--   PRIMARY KEY (`id`)
-- ) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=utf8;